kumuluzee:
  name: customers
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8080
    http:
      port: 8080
  discovery:
    etcd:
      hosts: http://localhost:2379 #http://192.168.99.100:2379
  config:
    etcd:
      hosts: http://localhost:2379 #http://192.168.99.100:2379
  health:
    checks:
      disk-space-health-check:
        threshold: 100000000
  metrics:
      web-instrumentation:
        - name: customers-endpoint
          url-pattern: /v1/customers/*
  logs:
      config-file: '<?xml version="1.0" encoding="UTF-8"?>
                    <Configuration name="customers">
                        <Appenders>
                            <Console name="console" target="SYSTEM_OUT">
                                <PatternLayout pattern="%d %p %marker %m %X %ex %n"/>
                            </Console>
                            <Socket name="logstash" host="66f3b286-2908-4800-9b50-5f9726aeb237-ls.logit.io" port="21189"
                                                                 protocol="tcp">
                                <JSONLayout complete="false" compact="true" eventEol="true" charset="UTF-8" properties="true"/>
                            </Socket>
                        </Appenders>
                        <Loggers>
                            <!-- Default logger -->
                            <Root level="all">
                                <AppenderRef ref="console" level="info"/>
                                <AppenderRef ref="logstash" level="trace"/>
                            </Root>
                        </Loggers>
                    </Configuration>'
rest-properties:
  external-services:
    apartment-service:
      enabled: true
  healthy: true